Repository baloise-incubator/design-system, pull requests merged in 2022-09, with the labels that each got.

#429 chore(stage): change colors of the stage to the lighter ones
  packages/components/src/components/bal-shape/bal-shape.tsx
  packages/components/src/components/bal-stage/bal-stage.sass
Labels: 💅 Style Issue

#451 chore(list): change default list item title level to h5 and set h4 in…
  packages/components/src/components/bal-list/bal-list-item-title/bal-list-item-title.tsx
  packages/components/src/components/bal-navigation/bal-navigation.tsx
Labels: 🐛 Bug

#433 fix(closable-popover): fix the click outside on popover
  packages/components/src/components.d.ts
  packages/components/src/components/bal-navigation/bal-navigation-popover/bal-navigation-popover.tsx
  packages/components/src/components/bal-navigation/stories/bal-navigation.stories.ts
  packages/components/src/components/bal-popover/bal-popover.tsx
Labels: ✋ ! DO NOT MERGE !

#464 chore(input): add allowedKeyPress prop and pass required in textarea …
  packages/components/src/components.d.ts
  packages/components/src/components/form/bal-input/bal-input.tsx
  packages/components/src/components/form/bal-input/stories/bal-input.stories.ts
  packages/components/src/components/form/bal-textarea/bal-textarea.tsx
Labels: 🐛 Bug

#481 454 bal datepicker buttons auto submit form
  .build/copy.js
  .gitignore
  packages/components/package.json
  packages/components/src/components.d.ts
  packages/components/src/components/bal-button/bal-button-group/bal-button-group.tsx
  packages/components/src/components/bal-card/bal-card-actions/bal-card-actions.tsx
  packages/components/src/components/bal-close/bal-close.tsx
  packages/components/src/components/bal-hint/bal-hint.sass
  packages/components/src/components/bal-hint/bal-hint.tsx
  packages/components/src/components/bal-icon/bal-icon.sass
  packages/components/src/components/bal-icon/bal-icon.tsx
  packages/components/src/components/bal-tag/bal-tag.sass
  packages/components/src/components/bal-tag/bal-tag.tsx
  packages/components/src/components/form/bal-checkbox/bal-checkbox-group/bal-checkbox-group.sass
  packages/components/src/components/form/bal-checkbox/bal-checkbox-group/bal-checkbox-group.tsx
  packages/components/src/components/form/bal-checkbox/bal-checkbox.sass
  packages/components/src/components/form/bal-checkbox/bal-checkbox.tsx
  packages/components/src/components/form/bal-checkbox/bal-switch.sass
  packages/components/src/components/form/bal-checkbox/stories/bal-checkbox.stories.ts
  packages/components/src/components/form/bal-datepicker/bal-datepicker.tsx
  packages/components/src/components/form/bal-field/bal-field.sass
  packages/components/src/components/form/bal-field/bal-field.tsx
  packages/components/src/components/form/bal-file-upload/bal-file-upload.tsx
  packages/components/src/components/form/bal-form-grid/bal-form-col/bal-form-col.tsx
  packages/components/src/components/form/bal-form-grid/bal-form-grid.sass
  packages/components/src/components/form/bal-form-grid/bal-form-grid.tsx
  packages/components/src/components/form/bal-form-grid/stories/bal-form-grid.stories.ts
  packages/components/src/components/form/bal-input-group/bal-input-group.sass
  packages/components/src/components/form/bal-input-stepper/bal-input-stepper.tsx
  packages/components/src/components/form/bal-input/bal-input.tsx
  packages/components/src/components/form/bal-number-input/bal-number-input.tsx
  packages/components/src/components/form/bal-radio/bal-radio-group/bal-radio-group.tsx
  packages/components/src/components/form/bal-radio/bal-radio.mixins.sass
  packages/components/src/components/form/bal-radio/bal-radio.sass
  packages/components/src/components/form/bal-radio/bal-radio.tsx
  packages/components/src/components/form/bal-select/bal-select.sass
  packages/components/src/components/form/bal-select/bal-select.tsx
  packages/components/src/components/form/bal-textarea/bal-textarea.tsx
  packages/components/src/helpers/form-input.helpers.ts
  packages/components/src/props.d.ts
  packages/components/src/styles/components/_all.sass
  packages/components/src/styles/components/radio-checkbox.mixins.sass
  packages/components/src/styles/components/radio-checkbox.sass
  packages/components/src/utils/observer.ts
  packages/components/src/utils/toggle-scrolling-body.ts
  packages/css/scss/form/file.sass
  packages/testing/src/commands/helpers.ts
  packages/testing/src/index.ts
  packages/tokens/src/index.ts
Labels: 🐛 Bug, 🧑‍💻 Technical Design System

#446 Feat/#359 animated logo
  packages/components-table/package-lock.json
  packages/components-table/package.json
  packages/components/package-lock.json
  packages/components/src/components.d.ts
  packages/components/src/components/bal-logo/bal-logo.animation.ts
  packages/components/src/components/bal-logo/bal-logo.sass
  packages/components/src/components/bal-logo/bal-logo.tsx
  packages/components/src/components/bal-logo/readme.md
  packages/components/src/components/bal-logo/stories/bal-logo.stories.ts
  packages/components/src/components/bal-navbar/bal-navbar-brand/bal-navbar-brand.tsx
  packages/components/src/components/bal-navigation/bal-navigation.tsx
  packages/components/src/components/bal-spinner/bal-spinner.sass
  packages/css/package-lock.json
  packages/fonts/package-lock.json
  packages/icons/package-lock.json
  packages/tokens/package-lock.json
Labels: 🆕 Enhancement

#475 chore(badge): replace selectors for the color classes
  packages/components/src/components/bal-badge/bal-badge.sass
Labels: 🐛 Bug, 🧑‍💻 Technical Design System, 💅 Style Issue

#507 fix(token): add inheritance and import the css vars once
  .build/generate-css-utils.js
  .build/tokens-generator.js
  .gitignore
  .prettierignore
  packages/components/src/components/bal-shape/bal-shape.tsx
  packages/components/src/components/docs/bal-doc-tokens/bal-doc-tokens-border-radius.tsx
  packages/components/src/components/docs/bal-doc-tokens/bal-doc-tokens-border.tsx
  packages/components/src/components/docs/bal-doc-tokens/bal-doc-tokens-breakpoints.tsx
  packages/components/src/components/docs/bal-doc-tokens/bal-doc-tokens-colors.tsx
  packages/components/src/components/docs/bal-doc-tokens/bal-doc-tokens-font-sizes.tsx
  packages/components/src/components/docs/bal-doc-tokens/bal-doc-tokens-font-weight.tsx
  packages/components/src/components/docs/bal-doc-tokens/bal-doc-tokens-shadow.tsx
  packages/components/src/components/docs/bal-doc-tokens/bal-doc-tokens-spacing.tsx
  packages/css/scss/baloise-design-system.base.sass
  packages/css/scss/baloise-design-system.utilities.sass
  packages/css/scss/helpers/flexbox.helper.sass
  packages/css/scss/helpers/spacing.helper.sass
  packages/css/scss/mixins/general.mixin.sass
  packages/fonts/scss/fonts.sass
  packages/fonts/scss/fonts.scss
  packages/tokens/package.json
  packages/tokens/rollup.config.js
  packages/tokens/rollup.config.tokens.js
  packages/tokens/src/index.ts
  rollup.base.js
Labels: 🐛 Bug, 🧑‍💻 Technical Design System

#506 chore(button): change color of the info light button
  packages/components/src/components/bal-button/stories/bal-button.stories.ts
  packages/css/scss/form/button.sass
Labels: 🐛 Bug, 🧑‍💻 Technical Design System, 💅 Style Issue

#513 chore(field): added new prop for vertical aligment on mobile
  cspell.json
  packages/components/src/components.d.ts
  packages/components/src/components/form/bal-field/bal-field-control/bal-field-control.tsx
  packages/components/src/components/form/bal-field/bal-field.sass
  packages/components/src/components/form/bal-field/stories/bal-field.stories.ts
Labels: 🆕 Enhancement, 🧑‍💻 Technical Design System

#509 478 bal tabs the line of the active tab is not visible at first render if the tabs are used inside of a popover
  packages/components/src/components/bal-popover/stories/bal-popover.stories.ts
  packages/components/src/components/bal-tabs/bal-tabs.tsx
  packages/css/assets/fonts/BaloiseCreateHeadline-bold.woff
  packages/css/assets/fonts/BaloiseCreateHeadline-bold.woff2
  packages/css/assets/fonts/BaloiseCreateHeadline-light.woff
  packages/css/assets/fonts/BaloiseCreateHeadline-light.woff2
  packages/css/assets/fonts/BaloiseCreateText-bold.woff
  packages/css/assets/fonts/BaloiseCreateText-bold.woff2
  packages/css/assets/fonts/BaloiseCreateText-regular.woff
  packages/css/assets/fonts/BaloiseCreateText-regular.woff2
  packages/tokens/.tmp/index.esm.js
  packages/tokens/.tmp/index.esm.js.map
  packages/tokens/.tmp/index.js
  packages/tokens/.tmp/index.js.map
  packages/tokens/.tmp/types/index.d.ts
  packages/tokens/.tmp/types/tokens.d.ts
  packages/tokens/src/tokens.ts
Labels: 🐛 Bug, 🧑‍💻 Technical Design System

#519 chore(footer): open links in a new tab
  packages/components/src/components/bal-footer/bal-footer.tsx
Labels: 🐛 Bug, 🧑‍💻 Technical Design System

#518 chore(button): handle row and column props for button group
  packages/css/scss/form/tools.sass
Labels: 🐛 Bug, 🧑‍💻 Technical Design System

#522 496 navigationdesktop bug bucket
  .gitignore
  package-lock.json
  packages/components/cypress/snapshots/base/bal-tag.visual.cy.ts/tag-basic-base.png
  packages/components/cypress/snapshots/base/bal-tag.visual.cy.ts/tag-variants-base.png
  packages/components/src/components/bal-hint/bal-hint.tsx
  packages/components/src/components/bal-logo/bal-logo.sass
  packages/components/src/components/bal-logo/bal-logo.tsx
  packages/components/src/components/bal-navigation/bal-navigation-menu/bal-navigation-menu.tsx
  packages/components/src/components/bal-navigation/bal-navigation-meta/bal-navigation-meta.tsx
  packages/components/src/components/bal-navigation/bal-navigation-popover/bal-navigation-popover.tsx
  packages/components/src/components/bal-navigation/bal-navigation.sass
  packages/components/src/components/bal-navigation/bal-navigation.tsx
  packages/components/src/components/bal-navigation/stories/bal-navigation.stories.ts
  packages/components/src/components/bal-popover/bal-popover.sass
  packages/components/src/components/bal-popover/bal-popover.tsx
  packages/components/src/components/bal-popover/stories/bal-popover.stories.ts
  packages/components/src/components/bal-stage/bal-stage.sass
  packages/components/src/components/bal-tabs/bal-tabs.sass
  packages/components/src/components/form/bal-select/bal-select.sass
  packages/components/src/components/notice/bal-modal/bal-modal.tsx
  packages/components/src/components/notice/bal-modal/stories/bal-modal.stories.ts
  packages/components/src/index.ts
  packages/components/src/stories/assets/css/theme.css
  packages/components/src/stories/design/css.stories.ts
  packages/components/src/styles/components/radio-checkbox.sass
  packages/components/src/styles/global.core.sass
  packages/components/src/utils/toggle-scrolling-body.ts
  packages/css/scss/layout/container.sass
  packages/css/scss/variables/_all.sass
  packages/css/scss/variables/container.vars.sass
  packages/icons/.DS_Store
  packages/tokens/.tmp/index.esm.js
  packages/tokens/.tmp/index.esm.js.map
  packages/tokens/.tmp/index.js
  packages/tokens/.tmp/index.js.map
  packages/tokens/.tmp/types/index.d.ts
  packages/tokens/.tmp/types/tokens.d.ts
Labels: 🐛 Bug, 🧑‍💻 Technical Design System, BLOCKER

#541 chore(stage): add hasShapeHandler function in connectedCallback
  packages/components/src/components/bal-stage/bal-stage.tsx
Labels: 🐛 Bug, BLOCKER

#563 499 product slider product slider line break issue
  packages/components/src/components/bal-badge/bal-badge.sass
  packages/components/src/components/bal-card/bal-card.sass
  packages/components/src/components/bal-data/bal-data.sass
  packages/components/src/components/bal-navbar/bal-navbar.sass
  packages/components/src/components/bal-product-slider/bal-product-slider.sass
  packages/components/src/components/bal-tabs/bal-tabs.sass
  packages/components/src/components/bal-tag/bal-tag.sass
  packages/components/src/components/notice/bal-notification/bal-notification.sass
  packages/components/src/components/notice/bal-toast/bal-toast.sass
  packages/components/src/styles/components/radio-checkbox.sass
  packages/css/scss/form/button.sass
  packages/css/scss/form/file.sass
  packages/css/scss/form/tools.sass
  packages/css/scss/layout/list.sass
  packages/css/scss/layout/table.sass
Labels: 🐛 Bug, 🧑‍💻 Technical Design System, 💅 Style Issue

#545 Fix/sass list
  packages/components-angular/package-lock.json
  packages/components-table/package-lock.json
  packages/components/cypress/e2e/visual/bal-list.visual.cy.ts
  packages/components/cypress/snapshots/base/bal-list.visual.cy.ts/list-backgrounds-base-1663416382490.png
  packages/components/cypress/snapshots/base/bal-list.visual.cy.ts/list-backgrounds-base.png
  packages/components/cypress/snapshots/base/bal-list.visual.cy.ts/list-basic-base-1663416382133.png
  packages/components/cypress/snapshots/base/bal-list.visual.cy.ts/list-basic-base.png
  packages/components/cypress/snapshots/base/bal-list.visual.cy.ts/list-sizes-base-1663416382362.png
  packages/components/cypress/snapshots/base/bal-list.visual.cy.ts/list-sizes-base.png
  packages/components/cypress/snapshots/base/bal-list.visual.cy.ts/list-variants-base-1663416382623.png
  packages/components/cypress/snapshots/base/bal-list.visual.cy.ts/list-variants-base.png
  packages/components/cypress/snapshots/base/bal-tag.visual.cy.ts/tag-basic-base.png
  packages/components/package-lock.json
  packages/components/src/components/bal-list/bal-list-item-accordion-body/bal-list-item-accordion-body.tsx
  packages/components/src/components/bal-list/bal-list-item-accordion-head/bal-list-item-accordion-head.tsx
  packages/components/src/components/bal-list/bal-list-item-content/bal-list-item-content.tsx
  packages/components/src/components/bal-list/bal-list-item-icon/bal-list-item-icon.tsx
  packages/components/src/components/bal-list/bal-list-item-subtitle/bal-list-item-subtitle.tsx
  packages/components/src/components/bal-list/bal-list-item-title/bal-list-item-title.tsx
  packages/components/src/components/bal-list/bal-list-item/bal-list-item.tsx
  packages/components/src/components/bal-list/bal-list.sass
  packages/components/src/components/bal-list/bal-list.scss
  packages/components/src/components/bal-list/bal-list.tsx
  packages/components/src/components/bal-list/stories/bal-list.stories.ts
  packages/components/src/components/bal-list/test/bal-list.cy..html
  packages/components/src/components/bal-list/test/bal-list.visual.html
  packages/components/src/components/bal-navigation/bal-navigation.tsx
  packages/components/src/styles/components/_all.sass
  packages/css/package-lock.json
  packages/testing/package-lock.json
Labels: 🐛 Bug, 🆕 Enhancement, 🧑‍💻 Technical Design System

#583 fix(list): passing click event of items content. Closes #582
  packages/components/src/components/bal-list/bal-list-item/bal-list-item.tsx
Labels: 🐛 Bug, BLOCKER

#663 feat(list): synchronices the accrodion bodies is set
  packages/components/src/components.d.ts
  packages/components/src/components/bal-list/bal-list-item-accordion-body/bal-list-item-accordion-body.tsx
  packages/components/src/components/bal-list/bal-list.sass
  packages/components/src/components/bal-list/stories/bal-list.stories.ts
Labels: 🆕 Enhancement
