Repository baloise-incubator/design-system, pull requests merged in 2022-10, with the labels that each got.

#670 fix(): verify if window object exist when checking if current browser…
  packages/components/src/utils/browser.ts
Labels: 🐛 Bug, ⚠️ BLOCKER

#671 chore(list): add prop for setting the justify content to the item-con…
  packages/components/src/components.d.ts
  packages/components/src/components/bal-list/bal-list-item-accordion-body/bal-list-item-accordion-body.tsx
  packages/components/src/components/bal-list/bal-list-item-content/bal-list-item-content.tsx
  packages/components/src/components/bal-list/bal-list.sass
  packages/components/src/components/bal-list/stories/bal-list.stories.ts
  packages/components/src/props.d.ts
Labels: 🐛 Bug

#674 chore(snackbar): add fixed width for mobile, tablet and desktop
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-desktop-closed-top-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-desktop-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-desktop-popover-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-highDefinition-closed-top-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-highDefinition-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-highDefinition-popover-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-widescreen-closed-bottom-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-widescreen-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-widescreen-popover-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-touch-mobile-closed-top-base.png
  packages/components/cypress/snapshots/base/bal-snackbar.visual.cy.ts/snackbar-basic-base.png
  packages/components/cypress/snapshots/base/bal-snackbar.visual.cy.ts/snackbar-basic-mobile-base.png
  packages/components/cypress/snapshots/base/bal-snackbar.visual.cy.ts/snackbar-variants-base.png
  packages/components/cypress/snapshots/base/bal-snackbar.visual.cy.ts/snackbar-variants-mobile-base.png
  packages/components/src/components/notice/bal-snackbar/bal-snackbar.sass
Labels: 🐛 Bug, 💅 Style Issue

#678 chore(product-slider): add line-height to the label of the slider-item
  packages/components/src/components/bal-product-slider/bal-product-slider.sass
Labels: 🐛 Bug

#677 chore(list): add timeout for calcContentHeight function in componentD…
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-desktop-closed-top-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-desktop-popover-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-highDefinition-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-highDefinition-popover-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-widescreen-closed-bottom-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-widescreen-popover-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-touch-tablet-closed-top-base.png
  packages/components/src/components/bal-list/bal-list-item-accordion-body/bal-list-item-accordion-body.tsx
Labels: 🐛 Bug

#697 chore(bal-select): break label text, add text overflow ellipsis on in…
  packages/components/src/components/bal-popover/bal-popover.sass
  packages/components/src/components/form/bal-select/bal-select.sass
  packages/components/src/components/form/bal-select/stories/bal-select.stories.ts
Labels: 🐛 Bug

#701 chore(bal-list): adjust color of the bottom border on hover and activ…
  packages/components/src/components/bal-list/bal-list.sass
Labels: 🐛 Bug

#708 chore(bal-list): set color of the subtitle to blue
  packages/components/cypress/snapshots/base/bal-list.visual.cy.ts/list-basic-base.png
  packages/components/cypress/snapshots/base/bal-list.visual.cy.ts/list-variants-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-desktop-closed-bottom-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-desktop-closed-top-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-desktop-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-desktop-popover-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-highDefinition-closed-top-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-highDefinition-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-highDefinition-popover-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-widescreen-closed-bottom-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-widescreen-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-widescreen-popover-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-touch-mobile-closed-top-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-touch-tablet-closed-top-base.png
  packages/components/src/components/bal-list/bal-list.sass
Labels: 🐛 Bug

#710 chore(bal-footer): set flex direction to column on tablet
  packages/components/src/components/bal-footer/bal-footer.sass
Labels: 🐛 Bug

#723 chore(bal-popover): decrease content padding on tablet
  packages/components/src/components/bal-popover/bal-popover.sass
Labels: 🐛 Bug

#732 chore(bal-stage): rename SimpleStage story to Basic
  packages/components/src/components/bal-stage/stories/bal-stage.stories.ts
Labels: 📘 Documentation

#739 580 datepickerdesktopsafarifirefox weekdays are not aligned with the cells
  packages/components/src/components.d.ts
  packages/components/src/components/bal-list/bal-list-item-accordion-body/bal-list-item-accordion-body.tsx
  packages/components/src/components/form/bal-datepicker/bal-datepicker.sass
Labels: 🐛 Bug, 🧑‍💻 Technical Design System, 📦 Release

#738 fix(list): listen to resize change of the accordion body
  packages/components/src/components/bal-list/bal-list-item-accordion-body/bal-list-item-accordion-body.tsx
Labels: 🐛 Bug, 🧑‍💻 Technical Design System, 📦 Release

#735 perf(button): only active lottie when loading is true
  packages/components/src/components.d.ts
  packages/components/src/components/bal-button/bal-button.tsx
  packages/components/src/components/bal-button/test/bal-button.perf.html
  packages/components/src/components/bal-logo/bal-logo.tsx
  packages/components/src/components/bal-navigation/bal-navigation.tsx
  packages/components/src/components/bal-navigation/test/bal-navigation.perf.html
  packages/components/src/components/bal-spinner/bal-spinner.tsx
Labels: 🧑‍💻 Technical Design System, 🚀 Performance, 📦 Release

#730 fix(navigation): do not block scrolling when a link is clicked
  packages/components/src/components.d.ts
  packages/components/src/components/bal-app/bal-app.tsx
  packages/components/src/components/bal-navigation/bal-navigation.sass
  packages/components/src/components/bal-navigation/bal-navigation.tsx
  packages/components/src/components/bal-tabs/bal-tabs.tsx
  packages/components/src/components/docs/bal-doc-app/bal-doc-app.tsx
Labels: 🐛 Bug, 🧑‍💻 Technical Design System, 📦 Release

#764 perf: use custom bundles and do not ship doc components
  packages/components-angular/package-lock.json
  packages/components-table/package-lock.json
  packages/components/config/doc.components.ts
  packages/components/config/stencil.basic.config.ts
  packages/components/package-lock.json
  packages/components/src/components/bal-button/test/bal-button.perf.html
  packages/components/stencil.config.dev.ts
  packages/components/stencil.config.e2e.ts
  packages/components/tsconfig.docs.json
  packages/components/tsconfig.json
  packages/css/package-lock.json
  packages/testing/package-lock.json
Labels: 🚀 Performance, 📦 Release

#778 755 set english as default language for date picker and number input
  packages/components/src/config/config.ts
  packages/components/src/config/config.types.ts
  packages/components/src/config/initialize.ts
Labels: 🐛 Bug

#779 chore(): increase add and commit version to 9
  .github/workflows/canary-release.yml
  .github/workflows/release.yml
  .github/workflows/visual-base.yml
Labels: 🏗️ Maintenance or Refactoring

#789 fix: check if window, document or navigator are existing
  packages/components/cypress/support/commands.ts
  packages/components/src/components.d.ts
  packages/components/src/components/bal-accordion/test/bal-accordion.visual.html
  packages/components/src/components/bal-badge/test/bal-badge.visual.html
  packages/components/src/components/bal-close/test/bal-close.visual.html
  packages/components/src/components/bal-data/test/bal-data.visual.html
  packages/components/src/components/bal-heading/test/bal-heading.visual.html
  packages/components/src/components/bal-list/test/bal-list.visual.html
  packages/components/src/components/bal-shape/test/bal-shape.visual.html
  packages/components/src/components/bal-stage/test/bal-stage.large.visual.html
  packages/components/src/components/bal-stage/test/bal-stage.visual.html
  packages/components/src/components/bal-tag/test/bal-tag.visual.html
  packages/components/src/components/bal-text/test/bal-text.visual.html
  packages/components/src/components/notice/bal-modal/bal-modal.controller.ts
  packages/components/src/components/notice/bal-notification/test/bal-notification.visual.html
  packages/components/src/components/notice/bal-snackbar/test/bal-snackbar.visual.html
  packages/components/src/components/notice/bal-toast/test/bal-toast.visual.html
  packages/components/src/global.ts
  packages/components/src/utils/browser.ts
  packages/components/src/utils/config/config.ts
  packages/components/src/utils/config/index.ts
  packages/components/src/utils/config/initialize.ts
  packages/components/src/utils/overlays/notice.controller.ts
  packages/components/src/utils/overlays/overlays.ts
  packages/components/src/utils/platform.ts
  packages/components/src/utils/resize.ts
  packages/components/src/utils/toggle-scrolling-body.ts
Labels: 🐛 Bug

#802 Fix/angular inital load
  packages/components/src/components/form/bal-select/bal-select.tsx
Labels: 🐛 Bug

#801 fix: add hammerjs as a dep of the core lib
  package-lock.json
  package.json
  packages/components/package-lock.json
  packages/components/package.json
Labels: 🐛 Bug
