Repository baloise-incubator/design-system, pull requests merged in 2022-11, with the labels that each got.

#850 844 load lottie lazy
  CHANGELOG.md
  packages/components/cypress/e2e/visual/bal-navigation.visual.cy.ts
  packages/components/cypress/snapshots/base/bal-footer.visual.cy.ts/footer-desktop-base.png
  packages/components/cypress/snapshots/base/bal-footer.visual.cy.ts/footer-mobile-base.png
  packages/components/cypress/snapshots/base/bal-footer.visual.cy.ts/footer-tablet-base.png
  packages/components/cypress/snapshots/base/bal-footer.visual.cy.ts/footer-variants-desktop-base.png
  packages/components/cypress/snapshots/base/bal-footer.visual.cy.ts/footer-variants-mobile-base.png
  packages/components/cypress/snapshots/base/bal-footer.visual.cy.ts/footer-variants-tablet-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-desktop-closed-bottom-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-desktop-closed-top-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-desktop-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-desktop-popover-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-highDefinition-closed-bottom-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-highDefinition-closed-top-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-highDefinition-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-highDefinition-popover-open-base.png
  packages/components/src/components/bal-footer/test/bal-footer.visual.html
  packages/components/src/components/bal-logo/Logo/Blue.svg
  packages/components/src/components/bal-logo/bal-logo.animation.ts
  packages/components/src/components/bal-logo/bal-logo.data.ts
  packages/components/src/components/bal-logo/bal-logo.large.tsx
  packages/components/src/components/bal-logo/bal-logo.small.tsx
  packages/components/src/components/bal-logo/bal-logo.tsx
  packages/components/src/components/bal-logo/test/bal-logo.perf.html
  packages/components/src/components/bal-spinner/bal-spinner.animation.ts
  packages/components/src/components/bal-spinner/bal-spinner.data.ts
  packages/components/src/components/bal-spinner/bal-spinner.tsx
  packages/components/src/utils/helpers.ts
Labels: 🚀 Performance

#849 782 bal tabs the line of the active tab is not visible at first render if the tabs are used inside of a accordion
  packages/components/src/components/bal-accordion/stories/bal-accordion.stories.ts
  packages/components/src/components/bal-tabs/bal-tabs.tsx
Labels: 🐛 Bug

#750 Perf/icons
  .build/optimize-icons.js
  .prettierignore
  packages/components/src/components.d.ts
  packages/components/src/components/bal-icon/bal-icon.tsx
  packages/components/src/components/bal-icon/stories/bal-icon.docs.mdx
  packages/components/src/components/bal-navigation/test/bal-navigation.visual.html
  packages/components/src/components/docs/bal-doc-app/bal-doc-app.tsx
  packages/components/src/stories/migration/10-migration-from-10x-to-11x.stories.mdx
  packages/components/src/stories/migration/99-migration-from-old-to-next.stories.mdx
  packages/components/src/utils/config/config.ts
  packages/components/src/utils/config/config.types.ts
  packages/components/src/utils/config/index.ts
  packages/components/src/utils/config/initialize.ts
  packages/components/src/utils/constants/icons.constant.ts
  packages/icons/src/icons.ts
  packages/icons/src/index.ts
  rollup.base.js
  tsconfig.base.json
Labels: 🧑‍💻 Technical Design System, 🚀 Performance, 📦 Release

#829 Refactoring Sliders -> Carousel
  .build/docs-contributors.js
  CHANGELOG.md
  packages/components/config/stencil.basic.config.ts
  packages/components/config/stencil.bindings.angular.ts
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-widescreen-closed-bottom-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-widescreen-closed-top-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-widescreen-open-base.png
  packages/components/cypress/snapshots/base/bal-navigation.visual.cy.ts/navigation-desktop-widescreen-popover-open-base.png
  packages/components/cypress/snapshots/base/bal-pagination.visual.cy.ts/pagination-small-with-dots-desktop-base.png
  packages/components/cypress/snapshots/base/bal-pagination.visual.cy.ts/pagination-small-with-dots-mobile-base.png
  packages/components/cypress/snapshots/base/bal-pagination.visual.cy.ts/pagination-small-with-dots-tablet-base.png
  packages/components/src/components.d.ts
  packages/components/src/components/bal-card/bal-card.sass
  packages/components/src/components/bal-carousel/bal-carousel-item/bal-carousel-item.tsx
  packages/components/src/components/bal-carousel/bal-carousel.sass
  packages/components/src/components/bal-carousel/bal-carousel.tsx
  packages/components/src/components/bal-carousel/bal-carousel.type.ts
  packages/components/src/components/bal-carousel/bal-carousel.vars.sass
  packages/components/src/components/bal-carousel/controls/dot-control.tsx
  packages/components/src/components/bal-carousel/controls/large-control.tsx
  packages/components/src/components/bal-carousel/controls/small-control.tsx
  packages/components/src/components/bal-carousel/controls/tab-control.tsx
  packages/components/src/components/bal-carousel/stories/bal-carousel.docs.mdx
  packages/components/src/components/bal-carousel/stories/bal-carousel.stories.ts
  packages/components/src/components/bal-carousel/stories/testing.md
  packages/components/src/components/bal-carousel/test/bal-carousel.perf.html
  packages/components/src/components/bal-image-slider/bal-image-slider-item/bal-image-slider-item.tsx
  packages/components/src/components/bal-image-slider/bal-image-slider.sass
  packages/components/src/components/bal-image-slider/bal-image-slider.tsx
  packages/components/src/components/bal-image-slider/stories/bal-image-slider.stories.ts
  packages/components/src/components/bal-image-slider/stories/testing.md
  packages/components/src/components/bal-image-slider/test/bal-image-slider.cy.html
  packages/components/src/components/bal-pagination/bal-pagination.sass
  packages/components/src/components/bal-pagination/bal-pagination.tsx
  packages/components/src/components/bal-product-slider/bal-product-slider.sass
  packages/components/src/components/bal-product-slider/bal-product-slider.tsx
  packages/components/src/components/bal-product-slider/stories/bal-product-slider.docs.mdx
  packages/components/src/components/bal-product-slider/stories/bal-product-slider.stories.ts
  packages/components/src/components/bal-product-slider/stories/testing.md
  packages/components/src/components/bal-slider/bal-slider-item/bal-slider-item.tsx
  packages/components/src/components/bal-slider/bal-slider.sass
  packages/components/src/components/bal-slider/bal-slider.tsx
  packages/components/src/components/bal-slider/stories/bal-slider.docs.mdx
  packages/components/src/components/bal-slider/stories/bal-slider.stories.ts
  packages/components/src/components/bal-slider/stories/testing.md
  packages/components/src/events.d.ts
  packages/components/src/props.d.ts
  packages/components/src/stories/contributors.md
  packages/components/src/stories/design/99-02-icons-common.stories.ts
  packages/components/src/styles/components/_all.sass
  packages/components/src/utils/observer.ts
  packages/components/src/utils/resize.ts
  packages/components/stencil.config.e2e.ts
  packages/css/scss/form/file.sass
  packages/css/scss/form/shared.sass
  packages/css/scss/helpers/others.helper.sass
  packages/css/scss/mixins/control.mixin.sass
Labels: 🆕 Enhancement, 🧑‍💻 Technical Design System, 🚀 Performance, 📦 Release
