Repository baloise-incubator/design-system, pull requests merged in 2022-08, with the labels that each got.

#335 chore: transform stencil e2e test to cypress components tests
  .github/workflows/continuous.yml
  package.json
  packages/components/cypress/component/bal-accordion.cy.ts
  packages/components/cypress/component/bal-button.cy.ts
  packages/components/cypress/component/bal-checkbox.cy.ts
  packages/components/cypress/component/bal-datepicker.cy.ts
  packages/components/cypress/component/bal-input.cy.ts
  packages/components/cypress/component/bal-number-input.cy.ts
  packages/components/cypress/component/bal-radio.cy.ts
  packages/components/cypress/component/bal-radio.vue
  packages/components/cypress/component/bal-select.cy.ts
  packages/components/cypress/component/bal-select.vue
  packages/components/cypress/component/bal-textarea.cy.ts
  packages/components/cypress/vite-env.d.ts
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/components/bal-accordion/test/bal-accordion.e2e.ts
  packages/components/src/components/bal-button/test/bal-button.e2e.ts
  packages/components/src/components/form/bal-checkbox/test/bal-checkbox.e2e.ts
  packages/components/src/components/form/bal-datepicker/test/bal-datepicker.e2e.ts
  packages/components/src/components/form/bal-input/test/bal-input.e2e.ts
  packages/components/src/components/form/bal-number-input/test/bal-number-input.e2e.ts
  packages/components/src/components/form/bal-radio/test/bal-radio.e2e.ts
  packages/components/src/components/form/bal-select/test/bal-select.e2e.ts
  packages/components/src/components/form/bal-textarea/test/bal-textarea.e2e.ts
Labels: 🧑‍💻 Technical Design System, 🏗️ Maintenance or Refactoring

#333 Chore/npm public
  README.md
  package.json
  packages/components-angular/README.md
  packages/components-angular/package.json
  packages/components-react/README.md
  packages/components-react/package.json
  packages/components-table/README.md
  packages/components-table/package.json
  packages/components-vue/README.md
  packages/components-vue/package.json
  packages/components/README.md
  packages/components/package.json
  packages/components/src/stories/assets/images/banner.svg
  packages/css/package.json
  packages/fonts/README.md
  packages/fonts/package.json
  packages/icons/README.md
  packages/icons/package.json
  packages/output-targets/angular/README.md
  packages/output-targets/angular/package.json
  packages/output-targets/react/README.md
  packages/output-targets/react/package.json
  packages/output-targets/vue/README.md
  packages/output-targets/vue/package.json
  packages/testing/README.md
  packages/testing/package.json
  packages/tokens/package.json
  resources/images/banner.svg
Labels: 🆕 Enhancement, 🧑‍💻 Technical Design System, 🏗️ Maintenance or Refactoring

#310 fix(image-slider): spacing adjusted and disabled arrows styled
  packages/components/src/components.d.ts
  packages/components/src/components/bal-image-slider/bal-image-slider.sass
  packages/components/src/components/bal-image-slider/bal-image-slider.tsx
  packages/components/src/components/bal-image-slider/stories/bal-image-slider.stories.ts
Labels: 🧑‍💻 Technical Design System, 💅 Style Issue

#339 chore(bal-data): add example for editable multiline and fix focus
  packages/components/src/components/bal-data/bal-data.sass
  packages/components/src/components/bal-data/stories/bal-data.stories.ts
Labels: 🐛 Bug

#340 fix(bal-data): fix font-weight in hint
  packages/components/src/components/bal-data/bal-data.sass
Labels: 🐛 Bug

#341 chore: update readme
  README.md
  packages/components-angular/README.md
  packages/components-react/README.md
  packages/components-table/README.md
  packages/components-vue/README.md
  packages/components/README.md
  packages/components/package.json
  packages/components/src/stories/welcome.stories.mdx
  packages/fonts/README.md
  packages/icons/README.md
  packages/output-targets/angular/README.md
  packages/output-targets/react/README.md
  packages/output-targets/vue/README.md
  packages/testing/README.md
  resources/images/baloise.svg
  resources/images/banner.svg
  resources/images/logo.png
  resources/images/logo.svg
Labels: 📘 Documentation

#348 fix: form elements height and placement
  packages/components/.storybook/bal.theme.js
  packages/components/cypress/component/bal-select.cy.ts
  packages/components/src/components/bal-icon/bal-icon.sass
  packages/components/src/components/bal-popover/bal-popover.scss
  packages/components/src/components/bal-popover/bal-popover.tsx
  packages/components/src/components/form/bal-datepicker/bal-datepicker.scss
  packages/components/src/components/form/bal-datepicker/bal-datepicker.tsx
  packages/components/src/components/form/bal-datepicker/stories/bal-datepicker.stories.ts
  packages/components/src/components/form/bal-input-group/bal-input-group.sass
  packages/components/src/components/form/bal-select/bal-select.scss
  packages/components/src/components/form/bal-select/bal-select.tsx
  packages/components/src/stories/assets/images/baloise.svg
  packages/components/src/stories/assets/images/favicon/android-chrome-192x192.png
  packages/components/src/stories/assets/images/favicon/android-chrome-512x512.png
  packages/components/src/stories/assets/images/favicon/apple-touch-icon.png
  packages/components/src/stories/assets/images/favicon/favicon-16x16.png
  packages/components/src/stories/assets/images/favicon/favicon-32x32.png
  packages/components/src/stories/assets/images/favicon/favicon.ico
  packages/components/src/stories/assets/images/favicon/site.webmanifest
  packages/components/src/stories/assets/images/storybook.svg
  packages/output-targets/vue/vue-component-lib/utils.ts
Labels: 🐛 Bug

#387 376 bal form container
  packages/components/.storybook/main.js
  packages/components/src/components.d.ts
  packages/components/src/components/form/bal-field/bal-field.tsx
  packages/components/src/components/form/bal-form/bal-form.tsx
  packages/components/src/components/form/bal-form/stories/bal-form.docs.mdx
  packages/components/src/components/form/bal-form/stories/bal-form.stories.ts
  packages/components/src/components/form/bal-form/stories/testing.md
  packages/components/src/index.ts
  packages/components/src/stories/utils/parameter.ts
  packages/components/src/stories/utils/story.ts
  packages/components/src/utils/form.ts
  packages/css/scss/form/button.sass
Labels: 🐛 Bug, 🆕 Enhancement

#428 fix(form): adjust input-group, radio alignment
  packages/components/src/components/form/bal-input-group/bal-input-group.sass
  packages/components/src/components/form/bal-input-group/stories/bal-input-group.stories.ts
  packages/components/src/components/form/bal-radio/bal-radio.sass
  packages/components/src/components/form/bal-select/bal-select.sass
  packages/css/scss/form/input-textarea.sass
  packages/css/scss/helpers/grid.helper.sass
Labels: 🐛 Bug

#431 chore(icons): add mobile and user-check icons
  packages/icons/src/icons.ts
  packages/icons/svg/mobile.svg
  packages/icons/svg/user-check.svg
Labels: 🆕 Enhancement

#430 chore(list): add 4px more to the margin right only on check icon
  packages/css/scss/layout/list.sass
Labels: 💅 Style Issue
