Repository baloise-incubator/design-system, pull requests merged in 2023-02, with the labels that each got.

#1146 feat(bal-input): add Belgian specific input masks
  cspell.json
  packages/components/src/components.d.ts
  packages/components/src/components/form/bal-input/bal-input-util.ts
  packages/components/src/components/form/bal-input/bal-input.tsx
  packages/components/src/components/form/bal-input/test/bal-input-util.spec.ts
  packages/components/src/props.d.ts
Labels: 🆕 Enhancement, 🧑‍💻 Technical Design System

#1153 feat: add waitForComponent util function
  .changeset/smart-ravens-rule.md
  cspell.json
  packages/components/src/components/bal-heading/bal-heading.tsx
  packages/components/src/index.ts
  packages/components/src/stories/development/guides/22-testing.stories.mdx
  packages/components/src/stories/foundation/brand-assets/00-overview.stories.mdx
  packages/components/src/utils/helpers.ts
Labels: 🆕 Enhancement

#1150 13/deprecated-styles
  CHANGELOG_NEXT.md
  packages/components/config/stencil.basic.config.ts
  packages/components/src/components.d.ts
  packages/components/src/components/bal-app/bal-app.tsx
  packages/components/src/components/docs/bal-doc-color/bal-doc-color.sass
  packages/components/src/components/docs/bal-doc-stackblitz/bal-doc-stackblitz.sass
  packages/components/src/styles/components.sass
  packages/components/src/styles/global.all.sass
  packages/components/src/styles/global.base.sass
  packages/components/src/styles/global.core.sass
  packages/components/src/styles/global.fonts.sass
  packages/components/src/styles/global.helpers.sass
  packages/components/src/styles/global.sass
  packages/components/src/styles/global.utilities.sass
  packages/components/src/styles/global.variables.sass
  packages/css/package.json
  packages/css/sass/baloise-design-system.sass
  packages/css/scss/baloise-design-system.base.sass
  packages/css/scss/baloise-design-system.fonts.sass
  packages/css/scss/baloise-design-system.helpers.sass
  packages/css/scss/baloise-design-system.layout.sass
  packages/css/scss/baloise-design-system.sass
  packages/css/scss/baloise-design-system.utilities.sass
  packages/css/scss/baloise-design-system.variables.sass
Labels: ✋ ! DO NOT MERGE !, v13

#1182 fix: adjust package.json to npm workspace structure and move contact.…
  .changeset/stupid-seas-glow.md
  .github/workflows/continuous.yml
  package-lock.json
  package.json
  packages/components-angular/package-lock.json
  packages/components-react/package-lock.json
  packages/components-table/package-lock.json
  packages/components-vue/package-lock.json
  packages/components/package-lock.json
  packages/components/package.json
  packages/components/src/components.d.ts
  packages/css/package-lock.json
  packages/fonts/package-lock.json
  packages/icons/package-lock.json
  packages/output-targets/angular/package-lock.json
  packages/output-targets/react/package-lock.json
  packages/output-targets/vue/package-lock.json
  packages/testing/package-lock.json
  packages/tokens/package-lock.json
Labels: 🐛 Bug
